//============================================================================
// Name        : wordshooter.cpp
// Author      : Huzaifa Mudassar
// Version     : 1
// Copyright   : (c) Reserved
// Description : Basic 2D game of Word Shooter
//============================================================================
#ifndef WORD_SHOOTER_CPP
#define WORD_SHOOTER_CPP
/*#include <GL/gl.h>
#include <GL/glut.h>*/
#include <iostream>
#include <string>
#include <cmath>
#include <fstream>
#include <SDL2/SDL.h>
#include <SDL2/SDL_mixer.h>
#include "util.h"
using namespace std;
float hx[30] = {465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465, 465}; //array for storing x-coordinates of shooter bubbles. Initialized to 465 for 30 bubbles.
float hy[30] = {10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10}; //array for storing y-coordinates of shooter bubbles. Initialized to 10 for 30 bubbles.
int index1 = 0; //counter variable for alternating between the shooter bubbles.
float slope; //slope of bubble used for moving it with respect to the where the mouse is clicked.
float fx; //final x-axis value.
float fy; //final y-axis value.
float dy = 1; //difference between final and initial x-axis values.
float dx = 3; //difference between final and initial y-axis values.
bool c = false; //bool for preventing unnecessary shooter bubble movement.
bool c1 = true; //bool for controlling when the other shooting bubble can move.
float tl = 150; //timer initialized to 150 seconds.
float path; //length of the path calculated by taking magnitude of dy and dx.
float incrx; //increments in shooter bubble's movement across the x-axis.
float incry; //increments in shooter bubble's movement across the y-axis.
int bubble[4][15]; //integer array used to storing the ascii values generated by the randomizer.
char cbub[4][15]; //character array used for storing the character names of shooting bubbles.
int col; //column of the shooting ball when it reaches the third row.
int row; //row of the bubble when it reaches beneath the second row.
int alphanum = 0; //variable to store the ascii values to be used for performing checks.
int xball[30]; //x-axis value array used for drawing the first two rows of bubbles.
int yball[30]; //y-axis value array used for drawing the first two rows of bubbles.
int ball[50]; //array for storing the 50 values given by randomizer function.
bool wpop = true; //bool for chcking words.

#define MAX(A, B) ((A) > (B) ? (A) : (B)) // defining single line functions....
#define MIN(A, B) ((A) < (B) ? (A) : (B))
#define ABS(A) ((A) < (0) ? -(A) : (A))
#define FPS 30 //controlling the game's frames per second.

string *dictionary;
int dictionarysize = 369646.; //the amount of words in the dictionary.
#define KEY_ESC 27 // A

// 20,30,30
const int bradius = 30; // ball radius in pixels...

int width = 930, height = 660;
int byoffset = bradius;

int nxcells = (width - bradius) / (2 * bradius);
int nycells = (height - byoffset /*- bradius*/) / (2 * bradius);
int nfrows = 2; // initially number of full rows //
float score = 0;
int **board; // 2D-arrays for holding the data...
int bwidth = 130;
int bheight = 10;
int bsx, bsy;
const int nalphabets = 26;
enum alphabets
{
    AL_A,
    AL_B,
    AL_C,
    AL_D,
    AL_E,
    AL_F,
    AL_G,
    AL_H,
    AL_I,
    AL_J,
    AL_K,
    AL_L,
    AL_M,
    AL_N,
    AL_O,
    AL_P,
    AL_Q,
    AL_R,
    AL_S,
    AL_T,
    AL_U,
    AL_W,
    AL_X,
    AL_y,
    AL_Z
};
GLuint texture[nalphabets];
GLuint tid[nalphabets];
string tnames[] = {"a.bmp", "b.bmp", "c.bmp", "d.bmp", "e.bmp", "f.bmp", "g.bmp", "h.bmp", "i.bmp", "j.bmp",
                   "k.bmp", "l.bmp", "m.bmp", "n.bmp", "o.bmp", "p.bmp", "q.bmp", "r.bmp", "s.bmp", "t.bmp", "u.bmp", "v.bmp", "w.bmp",
                   "x.bmp", "y.bmp", "z.bmp"};
GLuint mtid[nalphabets];
int awidth = 60, aheight = 60; // 60x60 pixels cookies...

// USED THIS CODE FOR WRITING THE IMAGES TO .bin FILE
void RegisterTextures_Write()
// Function is used to load the textures from the
//  files and display
{
    // allocate a texture name
    glGenTextures(nalphabets, tid);
    vector<unsigned char> data;
    ofstream ofile("image-data.bin", ios::binary | ios::out);
    // now load each cookies data...

    for (int i = 0; i < nalphabets; ++i)
    {

        // Read current cookie

        ReadImage(tnames[i], data);
        if (i == 0)
        {
            int length = data.size();
            ofile.write((char *)&length, sizeof(int));
        }
        ofile.write((char *)&data[0], sizeof(char) * data.size());

        mtid[i] = tid[i];
        // select our current texture
        glBindTexture(GL_TEXTURE_2D, tid[i]);

        // select modulate to mix texture with color for shading
        glTexEnvf(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);

        // when texture area is small, bilinear filter the closest MIP map
        glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER,
                        GL_LINEAR_MIPMAP_NEAREST);
        // when texture area is large, bilinear filter the first MIP map
        glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

        // if wrap is true, the texture wraps over at the edges (repeat)
        //       ... false, the texture ends at the edges (clamp)
        bool wrap = true;
        glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S,
                        wrap ? GL_REPEAT : GL_CLAMP);
        glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T,
                        wrap ? GL_REPEAT : GL_CLAMP);

        // build our texture MIP maps
        gluBuild2DMipmaps(GL_TEXTURE_2D, 3, awidth, aheight, GL_RGB,
                          GL_UNSIGNED_BYTE, &data[0]);
    }
    ofile.close();
}
void RegisterTextures()
/*Function is used to load the textures from the
 * files and display*/
{
    // allocate a texture name
    glGenTextures(nalphabets, tid);

    vector<unsigned char> data;
    ifstream ifile("image-data.bin", ios::binary | ios::in);

    if (!ifile)
    {
        cout << " Couldn't Read the Image Data file ";
        // exit(-1);
    }
    // now load each cookies data...
    int length;
    ifile.read((char *)&length, sizeof(int));
    data.resize(length, 0);
    for (int i = 0; i < nalphabets; ++i)
    {
        // Read current cookie
        // ReadImage(tnames[i], data);
        /*if (i == 0) {
        int length = data.size();
        ofile.write((char*) &length, sizeof(int));
        }*/
        ifile.read((char *)&data[0], sizeof(char) * length);

        mtid[i] = tid[i];
        // select our current texture
        glBindTexture(GL_TEXTURE_2D, tid[i]);

        // select modulate to mix texture with color for shading
        glTexEnvf(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);

        // when texture area is small, bilinear filter the closest MIP map
        glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER,
                        GL_LINEAR_MIPMAP_NEAREST);
        // when texture area is large, bilinear filter the first MIP map
        glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

        // if wrap is true, the texture wraps over at the edges (repeat)
        //       ... false, the texture ends at the edges (clamp)
        bool wrap = true;
        glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S,
                        wrap ? GL_REPEAT : GL_CLAMP);
        glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T,
                        wrap ? GL_REPEAT : GL_CLAMP);

        // build our texture MIP maps
        gluBuild2DMipmaps(GL_TEXTURE_2D, 3, awidth, aheight, GL_RGB,
                          GL_UNSIGNED_BYTE, &data[0]);
    }
    ifile.close();
}
void DrawAlphabet(const alphabets &cname, int sx, int sy, int cwidth = 60,
                  int cheight = 60)
/*Draws a specfic cookie at given position coordinate
 * sx = position of x-axis from left-bottom
 * sy = position of y-axis from left-bottom
 * cwidth= width of displayed cookie in pixels
 * cheight= height of displayed cookiei pixels.
 * */
{
    float fwidth = (float)cwidth / width * 2, fheight = (float)cheight / height * 2;
    float fx = (float)sx / width * 2 - 1, fy = (float)sy / height * 2 - 1;

    glPushMatrix();
    glEnable(GL_TEXTURE_2D);
    glBindTexture(GL_TEXTURE_2D, mtid[cname]);
    glBegin(GL_QUADS);
    glTexCoord2d(0.0, 0.0);
    glVertex2d(fx, fy);
    glTexCoord2d(1.0, 0.0);
    glVertex2d(fx + fwidth, fy);
    glTexCoord2d(1.0, 1.0);
    glVertex2d(fx + fwidth, fy + fheight);
    glTexCoord2d(0.0, 1.0);
    glVertex2d(fx, fy + fheight);
    glEnd();

    glColor4f(1, 1, 1, 1);

    //	glBindTexture(GL_TEXTURE_2D, 0);

    glDisable(GL_TEXTURE_2D);
    glPopMatrix();

    // glutSwapBuffers();
}
int GetAlphabet()
{
    return GetRandInRange(0, 25);
}

void Pixels2Cell(int px, int py, int &cx, int &cy)
{
}
void Cell2Pixels(int cx, int cy, int &px, int &py)
// converts the cell coordinates to pixel coordinates...
{
}
void DrawShooter(int sx, int sy, int cwidth = 60, int cheight = 60)

{
    float fwidth = (float)cwidth / width * 2, fheight = (float)cheight / height * 2;
    float fx = (float)sx / width * 2 - 1, fy = (float)sy / height * 2 - 1;

    glPushMatrix();
    glEnable(GL_TEXTURE_2D);
    glBindTexture(GL_TEXTURE_2D, -1);
    glBegin(GL_QUADS);
    glTexCoord2d(0.0, 0.0);
    glVertex2d(fx, fy);
    glTexCoord2d(1.0, 0.0);
    glVertex2d(fx + fwidth, fy);
    glTexCoord2d(1.0, 1.0);
    glVertex2d(fx + fwidth, fy + fheight);
    glTexCoord2d(0.0, 1.0);
    glVertex2d(fx, fy + fheight);
    glEnd();

    glColor4f(1, 1, 1, 1);

    //	glBindTexture(GL_TEXTURE_2D, 0);

    glDisable(GL_TEXTURE_2D);
    glPopMatrix();

    // glutSwapBuffers();
}
/*
 * Main Canvas drawing function.
 * */
void DisplayFunction()
{
    // set the background color using function glClearColor.
    // to change the background play with the red, green and blue values below.
    // Note that r, g and b values must be in the range [0,1] where 0 means dim red and 1 means pure red and so on.
    // #if 0
    glClearColor(1 /*Red Component*/, 0.0 /*Green Component*/,
                 0.0 /*Blue Component*/, 1 /*Alpha component*/); // Red==Green==Blue==1 --> White Colour
    glClear(GL_COLOR_BUFFER_BIT);                                // Update the colors

    static int no = GetAlphabet(); //variable for storing random numbers between 1 and 25.
    srand(no); //randomizing no.

    for (int no = 0; no < 50; no++) //loop for sotring random values for different alphabets.
    {
        ball[no] = GetAlphabet(); //calling GetAlphabte to assign one alphabet to ball array.
    }

    int k = 15; //variable used in the second row to not mix up the tw values of j for each of the rows.
    int x1 = 10; //width of first ball from left side.
    float bubheight = height / 1.2; //variable for storing the height of ball for the first row.
    for (int i = 0; i < 1; i++)
    {
        for (int j = 0; j < 15; j++) //loop for printing 15 balls in the first row.
        {
            xball[j] = x1; //x-axis width of bubble stored in array for printing.
            yball[j] = bubheight; //y-axis height of bubble stored in array for printing.
            DrawAlphabet((alphabets)ball[j], xball[j], yball[j], awidth, aheight); //printing bubbles.
            x1 += 60; //incrementing width by 60 to draw the next ball.
            bubble[i][j] = ball[j]; //storing the ball's ascii in the integer array.
        }
    }
    x1 = 10; //width resetted to 10 for printing the second row.
    bubheight = height / 1.35; //variable for storing the height of ball for the second row.
    for (int i = 1; i < 2; i++)
    {
        for (int j = 0; j < 15; j++) //loop for printing 15 balls in the first row.
        {
            xball[k] = x1; //x-axis width of bubble stored in array for printing.
            yball[k] = bubheight; //y-axis height of bubble stored in array for printing.
            DrawAlphabet((alphabets)ball[k], xball[k], yball[k], awidth, aheight); //printing bubbles.
            x1 += 60;  //incrementing width by 60 to draw the next ball.
            bubble[i][j] = ball[k]; //storing the ball's ascii in the integer array.
            k++; //incrementing alonside j;
        }
    }

    for (int i = 0; i < 1; i++) //row 1
    {
        for (int j = 0; j < 15; j++) //loop for converting int asciis into character.
        {
            cbub[i][j] = (bubble[i][j] + 97); //adding 97 to convert the integer ascii into character type to store in the character array.
        }
    }

    k = 15; //revaluating k again.
    for (int i = 1; i < 2; i++) //row 2
    {
        for (int j = 0; j < 15; j++) //loop for converting int asciis into character.
        {
            cbub[i][j] = (bubble[i][j] + 97); //adding 97 to convert the integer ascii into character type to store in the character array.
            k++; //taking k seperate because otherwise it conincides with j.
        }
    }

    // write your drawing commands here or call your drawing functions...
    DrawAlphabet((alphabets)ball[25], hx[0], hy[0], awidth, aheight); //printing first shooter ball.
    alphanum = ball[25]; //scoring the random ascii of the ball in alphanum.

    int l = 8; //variable 1 controlling the ball array element number.
    int m = 1; //variable 2 controlling the x-axis distance of shooter bubble.
    int n = 1; //variable 3 controlling the y-axis distance of shooter bubble.
    int y; //varibale for alternating between the 30 shooter balls initialized gloablly.
    for (y = 0; y < 30; y++) //loop for checking all the balls.
    {
        if (hy[y] > 425) //if ball has reached just below the secind row.
        {
            DrawAlphabet((alphabets)ball[l], hx[m], hy[n], awidth, aheight); //draw the other shooter ball.
            alphanum = ball[l]; //store it's ascii in alphanum like previously.
            l++;
            m++;
            n++;
        }
    }

    DrawString(620, height - 20, width, height + 5, "i24-0050 Huzaifa Mudassar", colors[WHITE]); //printing my name amd roll number on top of the canvas in white.
    DrawString(40, height - 20, width, height + 5, "Score " + Num2Str(score), colors[GREEN]); //changed color of score to green.
    DrawString(width / 2 - 130, height - 25, width, height,
               "Time Left:" + Num2Str(tl) + " secs", colors[BLUE]); //timer is blue.

    // #----------------- Write your code till here ----------------------------#
    // DO NOT MODIFY THESE LINES
    DrawShooter((width / 2) - 35, 0, bwidth, bheight);
    glutSwapBuffers();
    // DO NOT MODIFY THESE LINES..
}

/* Function sets canvas size (drawing area) in pixels...
 *  that is what dimensions (x and y) your game will have
 *  Note that the bottom-left coordinate has value (0,0) and top-right coordinate has value (width-1,height-1)
 * */
void SetCanvasSize(int width, int height)
{
    /*glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    glOrtho(0, width, 0, height, -1, 1); // set the screen size to given width and height.*/
}

/*This function is called (automatically) whenever any non-printable key (such as up-arrow, down-arraw)
 * is pressed from the keyboard
 *
 * You will have to add the necessary code here when the arrow keys are pressed or any other key is pressed...
 *
 * This function has three argument variable key contains the ASCII of the key pressed, while x and y tells the
 * program coordinates of mouse pointer when key was pressed.
 *
 * */

void NonPrintableKeys(int key, int x, int y)
{
    if (key == GLUT_KEY_LEFT /*GLUT_KEY_LEFT is constant and contains ASCII for left arrow key*/)
    {
        // what to do when left key is pressed...
    }
    else if (key == GLUT_KEY_RIGHT /*GLUT_KEY_RIGHT is constant and contains ASCII for right arrow key*/)
    {
    }
    else if (key == GLUT_KEY_UP /*GLUT_KEY_UP is constant and contains ASCII for up arrow key*/)
    {
    }
    else if (key == GLUT_KEY_DOWN /*GLUT_KEY_DOWN is constant and contains ASCII for down arrow key*/)
    {
    }

    /* This function calls the Display function to redo the drawing. Whenever you need to redraw just call
     * this function*/
    /*
    glutPostRedisplay();
    */
}
/*This function is called (automatically) whenever your mouse moves witin inside the game window
 *
 * You will have to add the necessary code here for finding the direction of shooting
 *
 * This function has two arguments: x & y that tells the coordinate of current position of move mouse
 *
 * */

void MouseMoved(int x, int y)
{
    // If mouse pressed then check than swap the balls and if after swaping balls dont brust then reswap the balls
}

/*This function is called (automatically) whenever your mouse button is clicked witin inside the game window
 *
 * You will have to add the necessary code here for shooting, etc.
 *
 * This function has four arguments: button (Left, Middle or Right), state (button is pressed or released),
 * x & y that tells the coordinate of current position of move mouse
 *
 * */

void MouseClicked(int button, int state, int x, int y)
{

    if (c1) //bool which is true inside the else of timer function.
    {
        if (button == GLUT_LEFT_BUTTON) // dealing only with left button
        {
            if (state == GLUT_UP) //mousepad's left top side.
            {
                fx = x; //final x-axis distance equalled to the point where mouse is clicked horizontally.
                fy = y; //final y-axis distance equalled to the point where mouse is clicked vertically.
                fy = 660 - fy; //subtracting it from 660 as the mouse clicked's inital position is at the top left and the height goes into negative below that.
                dy = fy - hy[index1]; //difference between final point and initial y-axis position.
                dx = fx - hx[index1]; //difference between final point and initial x-axis position.
                path = pow((dx * dx + dy * dy),0.5); //calculating the length of the path between the two differences.
                incrx = dx / path; //calculating increment of the bubble across the x-axis.
                incry = dy / path; //calculating increment of the bubble across the y-axis.
                incrx -= 0.1; //subtracting by0.1 to set the direction.
                incry -= 0.1; //subtracting by0.1 to set the direction.
                incrx *= 30; //multiplying by 30 to increase the speed of the movement.
                incry *= 30; //multiplying by 30 to increase the speed of the movement.
                c = true; //timer function can now be excuted.
            }
        }
    }
    else if (button == GLUT_RIGHT_BUTTON) // dealing with right button
    {
        if (state == GLUT_UP) //mousepad's right top side.
        {
                fx = x; //final x-axis distance equalled to the point where mouse is clicked horizontally.
                fy = y; //final y-axis distance equalled to the point where mouse is clicked vertically.
                fy = 660 - fy; //subtracting it from 660 as the mouse clicked's inital position is at the top left and the height goes into negative below that.
                dy = fy - hy[index1]; //difference between final point and initial y-axis position.
                dx = fx - hx[index1]; //difference between final point and initial x-axis position.
                path = pow((dx * dx + dy * dy),0.5); //calculating the length of the path between the two differences.
                incrx = dx / path; //calculating increment of the bubble across the x-axis.
                incry = dy / path; //calculating increment of the bubble across the y-axis.
                incrx -= 0.1; //subtracting by0.1 to set the direction.
                incry -= 0.1; //subtracting by0.1 to set the direction.
                incrx *= 30; //multiplying by 30 to increase the speed of the movement.
                incry *= 30; //multiplying by 30 to increase the speed of the movement.
                c = true; //timer function can now be excuted.      
        }
    }
    glutPostRedisplay();
}
/*This function is called (automatically) whenever any printable key (such as x,b, enter, etc.)
 * is pressed from the keyboard
 * This function has three argument variable key contains the ASCII of the key pressed, while x and y tells the
 * program coordinates of mouse pointer when key was pressed.
 * */
void PrintableKeys(unsigned char key, int x, int y)
{
    if (key == KEY_ESC /* Escape key ASCII*/)
    {
        exit(1); // exit the program when escape key is pressed.
    }
}

/*
 * This function is called after every 1000.0/FPS milliseconds
 * (FPS is defined on in the beginning).
 * You can use this function to animate objects and control the
 * speed of different moving objects by varying the constant FPS.
 *
 * */
void Timer(int m)
{
    tl = tl - 0.033; //timer decreased by 0.33 because fps is at 30 (3 times the initial) and the function is being called 10 times each second.
    if (tl == 0) //if time becomes zero.
    {
     exit(1); //exit the game.
    }
    if (c) //bool which was true inside mouse clicked.
    {
        c1 = false; //bool controlling the mouse clicked function
        hx[index1] += incrx; //incrementing the x-axis position by the x-incrment we calculated.
        hy[index1] += incry; //incrementing the y-axis position by the y-incrment we calculated.
        if ((hx[index1] >= (width - 60)) || (hx[index1] <= 0)) //if condition for the bubble when it reaches the border on either side.
        {
            incrx = -1.5*incrx; //increasing the speed of the bubble to make the game fun.
        }
        if (hy[index1] >= height / 1.54) //when the bubble reaches the third row.
        {
            incry = 0; //stop incrementing the current ball to make it stop.
            incrx = 0; //stop incrementing the current ball to make it stop.
            for (int x = 0; x < 50; x++) //checking condition for the 50 balls created.
            {
                if (hy[x] < 425) //if the ball is still in motion below the 3rd row, donot implement word logic.
                {
                }
                else //else this condition goes
                {
                    for (int row2 = 0; row2 < 3; row2++) //for checking the three row (2 initial and 1 with shooting bubbles.
                    {
                    if (wpop) //if popping word true.
                    {
                        string wr = ""; //initialize string to zero
                        for (int col2 = 0; col2 < 15; col2++) //checking the word in the 15 bubbles of the first row
                        {
                            if (cbub[row2][col2] != ' ') //if there is an ascii there instead of a space
                            {
                                wr += cbub[row2][col2]; //increment the string.
                                for (int i = 0; i < dictionarysize; i++) //loop checking throughout the whole dictionary.
                                {
                                    if (dictionary[i] == wr) //if the string word matches with the dictionary word
                                    {
                                        score += wr.size(); //increment the score with the amount of characters in the word
                                        wpop = false; //false the pop bool
                                        {
                                        ofstream frite; 
                                        frite.open ("Wordsfound.txt" , ios::out | ios::app); //opening a text file to store the popped words.
                                        frite << wr << "\n" ; //outputting the word.
                                        frite.close(); //closing the file.
                                        }
                                        break;
                                    }
                                }
                            }
                            else
                            {
                                wr = ""; //set the word back to zero
                            }
                        }
                    }    
                    }
                    for (int col2 = 0; col2 < 15; col2++) //checking the word in the 15 bubbles of the first row
                    {
                        string wr2 = ""; //initialize string to zero
                        for (int row2 = 0; row2 < 3; row2++) //for checking the three row (2 initial and 1 with shooting bubbles.
                        {
                            if (cbub[row2][col2] != ' ') //if there is an ascii there instead of a space
                            {
                                wr2 += cbub[row2][col2]; //increment the string.
                                for (int i = 0; i < dictionarysize; i++) //loop checking throughout the whole dictionary.
                                {
                                    if (dictionary[i] == wr2) //if the string word matches with the dictionary word
                                    {
                                        score += wr2.size(); //increment the score with the amount of characters in the word
                                        wpop = false; //false the pop bool
                                        {
                                        ofstream frite;
                                        frite.open ("Wordsfound.txt" , ios::out | ios::app); //opening a text file to store the popped words.
                                        frite << wr2 << "\n" ; //outputting the word.
                                        frite.close();  //closing the file.
                                        }
                                        break;
                                    }
                                }
                            }
                            else
                            {
                                wr2 = ""; //set the string back to zero
                            }
                        }
                    }
                }
            }

            col = (hx[index1] + bradius) / (2 * bradius); //mathematical equation for determining the column of the stuck bubble
            row = (height - hy[index1]) / (2 * bradius); //mathematical equation for determining the row of the stuck bubble
            if ((col >= 7) && (col <= 14)) //if column is to the right of the middle row
            {
                col += 1; //increase it by one
            }
            if (col >= 15) //if column is way beyond 15
            {
                col = 14; //make it 14
            }
            else if (col <= 6) //if column is to the left of the middle row
            {
                col += 1; //incrase it by one.
            }
            bubble[row][col] = alphanum; //stpring alphanum in the integer array
            cbub[row][col] = char(bubble[row][col] + 97); //converting the array into character array
            if ((col >= 7) && (col <= 14)) //if to the right of middle bubble
            {
                hx[index1] = ((col - 1) * 2 * bradius) + (width / 60); //x-axis width set by mathematical equation
            }
            else if (col <= 6) //if to the left of the middle bubble
            {
                hx[index1] = (col * 2 * bradius) - (width / 20); //x-axis width set by mathematical equation
            }
            else if (col >= 15) //if column above 15
            {
                hx[index1] = 900; //set the width of tghe printed ball to 900
            }
            hy[index1] = (height / 1.09) - (row * 2 * bradius); //setting the y-axis height
            index1++; //incrementing the index of hx,hy.
        }
        else
        {
            c1 = true; //true the function controlling mouse clicked.
        }
    }

    glutPostRedisplay();
    glutTimerFunc(1000.0 / FPS, Timer, 0);
}

/*
 * our gateway main function
 * */
int main(int argc, char *argv[])
{
    InitRandomizer(); // seed the random number generator...

    // Dictionary for matching the words. It contains the 370099 words.
    dictionary = new string[dictionarysize];
    ReadWords("words_alpha.txt", dictionary); // dictionary is an array of strings
    // print first 5 words from the dictionary
    for (int i = 0; i < 5; ++i)
        cout << " word " << i << " =" << dictionary[i] << endl;
        Mix_OpenAudio(44100,MIX_DEFAULT_FORMAT,2,2048);
        Mix_Music* bgMusic = Mix_LoadMUS("spinning-head-271171.mp3");
        Mix_PlayMusic(bgMusic,-1);
    // Write your code here for filling the canvas with different Alphabets. You can use the Getalphabet function for getting the random alphabets

    glutInit(&argc, argv);                               // initialize the graphics library...
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA);        // we will be using color display mode
    glutInitWindowPosition(50, 50);                      // set the initial position of our window
    glutInitWindowSize(width, height);                   // set the size of our window
    glutCreateWindow("Huzaifa Mudassar's Word Shooter"); // set the name of the terminal to name.
    // SetCanvasSize(width, height); // set the number of pixels...

    // Register your functions to the library,
    // you are telling the library names of function to call for different tasks.
    RegisterTextures();
    glutDisplayFunc(DisplayFunction);  // tell library which function to call for drawing Canvas.
    glutSpecialFunc(NonPrintableKeys); // tell library which function to call for non-printable ASCII characters
    glutKeyboardFunc(PrintableKeys);   // tell library which function to call for printable ASCII characters
    glutMouseFunc(MouseClicked);
    glutPassiveMotionFunc(MouseMoved); // Mouse

    //// This function tells the library to call our Timer function after 1000.0/FPS milliseconds...
    glutTimerFunc(1000.0 / FPS, Timer, 0);

    //// now handle the control to library and it will call our registered functions when
    //// it deems necessary...

    glutMainLoop();

    return 1;
}
#endif /* */
